Feature/update edge version
oat-sa/browserslist-config-tao pull request #5
Opened 2020-05-22 08:38 UTC by arcadiaEvgenyLokets

Update edge version in browserslist config

**How it test**
Run `npm run browserslist` and check browsers list

2020-05-22 12:26 UTC, krampstudio requested changes

2020-05-22 12:26 UTC, krampstudio commented on index.js
> +    'last 1 edge version',
You should still keep the last 2 version but if you update the version `browserslist` the supported version range will get updated

2020-05-22 12:40 UTC, btamas commented on package.json
> +    "version": "0.2.1",
Version should be `0.2.0`

2020-05-26 09:57 UTC, krampstudio approved these changes

2020-05-26 11:59 UTC, btamas approved these changes

2020-05-26 15:12 UTC, merged